# Generated by Django 3.1.2 on 2020-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name="Book's title")),
                ('cover', models.ImageField(upload_to='books/covers/', verbose_name="Book's cover")),
                ('authors', models.ManyToManyField(to='authors.Author')),
            ],
        ),
    ]
